[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#d4d4d4'

[colors.cursor]
text = '#131313'
cursor = '#ffffff'

[colors.normal]
black   = '#131313'
red     = '#ff7272'
green   = '#9bff7f'
yellow  = '#ffe372'
blue    = '#f2f2f2'
magenta = '#767676'
cyan    = '#ffffff'
white   = '#ffefef'

[colors.bright]
black   = '#a59999'
red     = '#ff9f9f'
green   = '#b9ffa5'
yellow  = '#ffeda5'
blue    = '#ffffff'
magenta = '#ffffff'
cyan    = '#ffffff'
white   = '#fff8f8'
