
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080@144",
    position = "auto",
    scale    = "1",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "ghostty"
local fileManager = "nautilus"
local menu        = "fuzzel"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
hl.on("hyprland.start", function () 
  -- Importante para o funcionamento correto do XDG Desktop Portal
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  
  -- Agente de Autenticação Polkit para pedir senha em modo gráfico (usando o polkit-gnome já instalado)
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  
  -- Inicia o Noctalia Shell em modo daemon
  hl.exec_cmd("noctalia --daemon")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GTK_THEME", "Adwaita-dark")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 10,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "scrolling",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})
-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("snappy",         { type = "bezier", points = { {0.15, 0.85}, {0.1, 1.0}   } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 3.5,  bezier = "snappy" })
hl.animation({ leaf = "border",        enabled = true,  speed = 4,    bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 3.2,  bezier = "snappy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 3.2,  bezier = "snappy",       style = "popin 85%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 2.8,  bezier = "snappy",       style = "popin 80%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 2.8,  bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 2.5,  bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.0,  bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.2,  bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 3.2,  bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 2.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 2.8,  bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 2.2,  bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 3.5,  bezier = "snappy",       style = "slidefade 20%" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 3.5,  bezier = "snappy",       style = "slidefade 20%" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 3.5,  bezier = "snappy",       style = "slidefade 20%" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 5,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
        wrap_focus = false,
        wrap_swapcol = false,
    },
})

hl.config({
    binds = {
        allow_workspace_cycles = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "br",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- --- APLICATIVOS E LAUNCHER ---
hl.bind(mainMod .. " + Return",    hl.dsp.exec_cmd(terminal))
hl.bind("CTRL + ALT + T",          hl.dsp.exec_cmd(terminal))
hl.bind("CTRL + space",            hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"))
hl.bind(mainMod .. " + B",         hl.dsp.exec_cmd("zen-browser"))
hl.bind(mainMod .. " + ALT + L",   hl.dsp.exec_cmd("noctalia msg session lock"))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("noctalia msg panel-toggle session"))
hl.bind("CTRL + ALT + C",          hl.dsp.exec_cmd("noctalia msg settings-toggle"))
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + Q",         hl.dsp.window.close())

-- --- CONTROLES DE MÍDIA (Noctalia IPC) ---
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("noctalia msg volume-up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("noctalia msg volume-down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("noctalia msg volume-mute"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("noctalia msg mic-mute"), { locked = true, repeating = true })
hl.bind("XF86AudioNext",         hl.dsp.exec_cmd("noctalia msg media next"), { locked = true })
hl.bind("XF86AudioPrev",         hl.dsp.exec_cmd("noctalia msg media previous"), { locked = true })
hl.bind("XF86AudioPlay",         hl.dsp.exec_cmd("noctalia msg media toggle"), { locked = true })
hl.bind("XF86AudioPause",        hl.dsp.exec_cmd("noctalia msg media toggle"), { locked = true })

-- --- BRILHO DA TELA (Noctalia IPC) ---
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("noctalia msg brightness-up"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("noctalia msg brightness-down"), { locked = true, repeating = true })

-- --- NAVEGAÇÃO DE FOCO (Setas / Vim / WASD) ---
local focus_directions = {
    l = {"left", "H", "A"},
    r = {"right", "L", "D"},
    u = {"up", "K", "W"},
    d = {"down", "J", "S"}
}
for dir, keys in pairs(focus_directions) do
    for _, key in ipairs(keys) do
        hl.bind(mainMod .. " + " .. key, hl.dsp.layout("focus " .. dir))
    end
end

-- --- MOVIMENTAÇÃO DE JANELAS (SUPER + CTRL + Setas / Vim / WASD) ---
local move_directions = {
    left =  {"left", "H", "A"},
    right = {"right", "L", "D"},
    up =    {"up", "K", "W"},
    down =  {"down", "J", "S"}
}
for dir, keys in pairs(move_directions) do
    for _, key in ipairs(keys) do
        hl.bind(mainMod .. " + CTRL + " .. key, hl.dsp.window.move({ direction = dir }))
    end
end

-- --- ALTERNAÇÃO E MOVIMENTAÇÃO DE WORKSPACES ---
for i = 1, 9 do
    hl.bind(mainMod .. " + " .. i,        hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + CTRL + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + TAB", hl.dsp.focus({ workspace = "previous" }))

-- --- ROLAGEM DE WORKSPACES COM MOUSE / TOUCHPAD ---
hl.bind(mainMod .. " + CTRL + mouse_down", hl.dsp.window.move({ workspace = "-1" }))
hl.bind(mainMod .. " + CTRL + mouse_up",   hl.dsp.window.move({ workspace = "+1" }))

-- --- ARRASTAR E REDIMENSIONAR JANELAS ---
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- --- CONTROLE DO LAYOUT (Modo Scroll) ---
hl.bind(mainMod .. " + M",     hl.dsp.window.fullscreen({ mode = 1, action = "toggle" }))
hl.bind(mainMod .. " + F",     hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind(mainMod .. " + T",     hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + C",     hl.dsp.layout("center"))
hl.bind(mainMod .. " + Minus", hl.dsp.layout("colresize -0.1"))
hl.bind(mainMod .. " + Equal", hl.dsp.layout("colresize +0.1"))

-- --- CAPTURAS DE TELA (Screenshots) ---
hl.bind("CTRL + SHIFT + 1", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))
hl.bind("CTRL + SHIFT + 2", hl.dsp.exec_cmd("grim - | wl-copy"))
hl.bind("CTRL + SHIFT + 3", hl.dsp.exec_cmd([[grim -g "$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" - | wl-copy]]))
hl.bind("ALT + P",            hl.dsp.exec_cmd("noctalia msg screenshot-region"))
hl.bind("ALT + bracketleft",  hl.dsp.exec_cmd("noctalia msg screenshot-fullscreen"))

-- --- SAÍDA ---
-- 'exit' é o dispatcher correto do hyprctl (o antigo "hyprctl dispatch
-- 'hl.dsp.exit()'" passava código Lua como dispatcher e não fazia nada).
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("hyprctl dispatch exit"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})

-- Regras para janelas flutuantes úteis (calculadora, pré-visualizações, diálogos)
hl.window_rule({
    name  = "float-utilities",
    match = { class = "gnome-calculator|org.gnome.NautilusPreviewer|file-roller|pavucontrol" },
    float = true,
})

hl.window_rule({
    name  = "float-dialogs",
    match = { title = "Open File|Save File|Confirm|Preferences|File Operation Progress" },
    float = true,
})

-- Forçar o Calibre (Preferências) a ser ladrilhado (tiled)
hl.window_rule({
    name  = "tile-calibre-preferences",
    match = { class = "calibre-gui", title = "calibre - Preferências" },
    float = false,
})

-- Definir opacidade para o Ghostty (Terminal)
hl.window_rule({
    name  = "ghostty-opacity",
    match = { class = "com.mitchellh.ghostty" },
    opacity = "0.9 0.8",
})

-- Efeito Blur desativado para o Noctalia Shell perante solicitação do usuário
